/*
 * Copyright (C) 2020-2022 Lura Skye.
 *
 * This file is part of Tinlok.
 *
 * Tinlok is dually released under the GNU Lesser General Public License,
 * Version 3 or later, or the Mozilla Public License 2.0.
 */

@file:Suppress("unused", "MayBeConstant", "SpellCheckingInspection")

package tf.veriny.tinlok.net.socket

/* Generated on a Linux box on 2020-11-15 */

internal val AF_ALG = 38
internal val AF_APPLETALK = 5
internal val AF_ASH = 18
internal val AF_ATMPVC = 8
internal val AF_ATMSVC = 20
internal val AF_AX25 = 3
internal val AF_BLUETOOTH = 31
internal val AF_BRIDGE = 7
internal val AF_CAN = 29
internal val AF_ECONET = 19
internal actual val AF_INET = 2
internal actual val AF_INET6 = 10
internal val AF_IPX = 4
internal val AF_IRDA = 23
internal val AF_KEY = 15
internal val AF_LLC = 26
internal val AF_NETBEUI = 13
internal val AF_NETLINK = 16
internal val AF_NETROM = 6
internal val AF_PACKET = 17
internal val AF_PPPOX = 24
internal val AF_QIPCRTR = 42
internal val AF_RDS = 21
internal val AF_ROSE = 11
internal val AF_ROUTE = 16
internal val AF_SECURITY = 14
internal val AF_SNA = 22
internal val AF_TIPC = 30
internal actual val AF_UNIX = 1
internal actual val AF_UNSPEC = 0
internal val AF_VSOCK = 40
internal val AF_WANPIPE = 25
internal val AF_X25 = 9
internal val AI_ADDRCONFIG = 32
internal val AI_ALL = 16
internal val AI_CANONNAME = 2
internal val AI_NUMERICHOST = 4
internal val AI_NUMERICSERV = 1024
internal val AI_PASSIVE = 1
internal val AI_V4MAPPED = 8
internal val ALG_OP_DECRYPT = 0
internal val ALG_OP_ENCRYPT = 1
internal val ALG_OP_SIGN = 2
internal val ALG_OP_VERIFY = 3
internal val ALG_SET_AEAD_ASSOCLEN = 4
internal val ALG_SET_AEAD_AUTHSIZE = 5
internal val ALG_SET_IV = 2
internal val ALG_SET_KEY = 1
internal val ALG_SET_OP = 3
internal val ALG_SET_PUBKEY = 6
internal val BTPROTO_HCI = 1
internal val BTPROTO_L2CAP = 0
internal val BTPROTO_RFCOMM = 3
internal val BTPROTO_SCO = 2
internal val CAN_BCM = 2
internal val CAN_BCM_CAN_FD_FRAME = 2048
internal val CAN_BCM_RX_ANNOUNCE_RESUME = 256
internal val CAN_BCM_RX_CHANGED = 12
internal val CAN_BCM_RX_CHECK_DLC = 64
internal val CAN_BCM_RX_DELETE = 6
internal val CAN_BCM_RX_FILTER_ID = 32
internal val CAN_BCM_RX_NO_AUTOTIMER = 128
internal val CAN_BCM_RX_READ = 7
internal val CAN_BCM_RX_RTR_FRAME = 1024
internal val CAN_BCM_RX_SETUP = 5
internal val CAN_BCM_RX_STATUS = 10
internal val CAN_BCM_RX_TIMEOUT = 11
internal val CAN_BCM_SETTIMER = 1
internal val CAN_BCM_STARTTIMER = 2
internal val CAN_BCM_TX_ANNOUNCE = 8
internal val CAN_BCM_TX_COUNTEVT = 4
internal val CAN_BCM_TX_CP_CAN_ID = 16
internal val CAN_BCM_TX_DELETE = 2
internal val CAN_BCM_TX_EXPIRED = 9
internal val CAN_BCM_TX_READ = 3
internal val CAN_BCM_TX_RESET_MULTI_IDX = 512
internal val CAN_BCM_TX_SEND = 4
internal val CAN_BCM_TX_SETUP = 1
internal val CAN_BCM_TX_STATUS = 8
internal val CAN_EFF_FLAG = 2147483648
internal val CAN_EFF_MASK = 536870911
internal val CAN_ERR_FLAG = 536870912
internal val CAN_ERR_MASK = 536870911
internal val CAN_ISOTP = 6
internal val CAN_RAW = 1
internal val CAN_RAW_ERR_FILTER = 2
internal val CAN_RAW_FD_FRAMES = 5
internal val CAN_RAW_FILTER = 1
internal val CAN_RAW_LOOPBACK = 3
internal val CAN_RAW_RECV_OWN_MSGS = 4
internal val CAN_RTR_FLAG = 1073741824
internal val CAN_SFF_MASK = 2047
internal val EAGAIN = 11
internal val EAI_ADDRFAMILY = -9
internal val EAI_AGAIN = -3
internal val EAI_BADFLAGS = -1
internal val EAI_FAIL = -4
internal val EAI_FAMILY = -6
internal val EAI_MEMORY = -10
internal val EAI_NODATA = -5
internal val EAI_NONAME = -2
internal val EAI_OVERFLOW = -12
internal val EAI_SERVICE = -8
internal val EAI_SOCKTYPE = -7
internal val EAI_SYSTEM = -11
internal val EBADF = 9
internal val EWOULDBLOCK = 11
internal val HCI_DATA_DIR = 1
internal val HCI_FILTER = 2
internal val HCI_TIME_STAMP = 3
internal val INADDR_ALLHOSTS_GROUP = 3758096385
internal val INADDR_ANY = 0
internal val INADDR_BROADCAST = 4294967295
internal val INADDR_LOOPBACK = 2130706433
internal val INADDR_MAX_LOCAL_GROUP = 3758096639
internal val INADDR_NONE = 4294967295
internal val INADDR_UNSPEC_GROUP = 3758096384
internal val IOCTL_VM_SOCKETS_GET_LOCAL_CID = 1977
internal val IPPORT_RESERVED = 1024
internal val IPPORT_USERRESERVED = 5000
internal val IPPROTO_AH = 51
internal val IPPROTO_DSTOPTS = 60
internal val IPPROTO_EGP = 8
internal val IPPROTO_ESP = 50
internal val IPPROTO_FRAGMENT = 44
internal val IPPROTO_GRE = 47
internal val IPPROTO_HOPOPTS = 0
internal actual val IPPROTO_ICMP = 1
internal val IPPROTO_ICMPV6 = 58
internal val IPPROTO_IDP = 22
internal val IPPROTO_IGMP = 2
internal actual val IPPROTO_IP = 0
internal val IPPROTO_IPIP = 4
internal val IPPROTO_IPV6 = 41
internal val IPPROTO_NONE = 59
internal val IPPROTO_PIM = 103
internal val IPPROTO_PUP = 12
internal val IPPROTO_RAW = 255
internal val IPPROTO_ROUTING = 43
internal val IPPROTO_RSVP = 46
internal val IPPROTO_SCTP = 132
internal actual val IPPROTO_TCP = 6
internal val IPPROTO_TP = 29
internal actual val IPPROTO_UDP = 17
internal val IPV6_CHECKSUM = 7
internal val IPV6_DONTFRAG = 62
internal val IPV6_DSTOPTS = 59
internal val IPV6_HOPLIMIT = 52
internal val IPV6_HOPOPTS = 54
internal val IPV6_JOIN_GROUP = 20
internal val IPV6_LEAVE_GROUP = 21
internal val IPV6_MULTICAST_HOPS = 18
internal val IPV6_MULTICAST_IF = 17
internal val IPV6_MULTICAST_LOOP = 19
internal val IPV6_NEXTHOP = 9
internal val IPV6_PATHMTU = 61
internal val IPV6_PKTINFO = 50
internal val IPV6_RECVDSTOPTS = 58
internal val IPV6_RECVHOPLIMIT = 51
internal val IPV6_RECVHOPOPTS = 53
internal val IPV6_RECVPATHMTU = 60
internal val IPV6_RECVPKTINFO = 49
internal val IPV6_RECVRTHDR = 56
internal val IPV6_RECVTCLASS = 66
internal val IPV6_RTHDR = 57
internal val IPV6_RTHDRDSTOPTS = 55
internal val IPV6_RTHDR_TYPE_0 = 0
internal val IPV6_TCLASS = 67
internal val IPV6_UNICAST_HOPS = 16
internal val IPV6_V6ONLY = 26
internal val IP_ADD_MEMBERSHIP = 35
internal val IP_DEFAULT_MULTICAST_LOOP = 1
internal val IP_DEFAULT_MULTICAST_TTL = 1
internal val IP_DROP_MEMBERSHIP = 36
internal val IP_HDRINCL = 3
internal val IP_MAX_MEMBERSHIPS = 20
internal val IP_MULTICAST_IF = 32
internal val IP_MULTICAST_LOOP = 34
internal val IP_MULTICAST_TTL = 33
internal val IP_OPTIONS = 4
internal val IP_RECVOPTS = 6
internal val IP_RECVRETOPTS = 7
internal val IP_RETOPTS = 7
internal val IP_TOS = 1
internal val IP_TRANSPARENT = 19
internal val IP_TTL = 2
internal val MSG_CMSG_CLOEXEC = 1073741824
internal val MSG_CONFIRM = 2048
internal val MSG_CTRUNC = 8
internal val MSG_DONTROUTE = 4
internal val MSG_DONTWAIT = 64
internal val MSG_EOR = 128
internal val MSG_ERRQUEUE = 8192
internal val MSG_FASTOPEN = 536870912
internal val MSG_MORE = 32768
internal val MSG_NOSIGNAL = 16384
internal val MSG_OOB = 1
internal val MSG_PEEK = 2
internal val MSG_TRUNC = 32
internal val MSG_WAITALL = 256
internal val NETLINK_CRYPTO = 21
internal val NETLINK_DNRTMSG = 14
internal val NETLINK_FIREWALL = 3
internal val NETLINK_IP6_FW = 13
internal val NETLINK_NFLOG = 5
internal val NETLINK_ROUTE = 0
internal val NETLINK_USERSOCK = 2
internal val NETLINK_XFRM = 6
internal val NI_DGRAM = 16
internal val NI_MAXHOST = 1025
internal val NI_MAXSERV = 32
internal val NI_NAMEREQD = 8
internal val NI_NOFQDN = 4
internal val NI_NUMERICHOST = 1
internal val NI_NUMERICSERV = 2
internal val PACKET_BROADCAST = 1
internal val PACKET_FASTROUTE = 6
internal val PACKET_HOST = 0
internal val PACKET_LOOPBACK = 5
internal val PACKET_MULTICAST = 2
internal val PACKET_OTHERHOST = 3
internal val PACKET_OUTGOING = 4
internal val PF_CAN = 29
internal val PF_PACKET = 17
internal val PF_RDS = 21
internal val SCM_CREDENTIALS = 2
internal val SCM_RIGHTS = 1
internal val SHUT_RD = 0
internal val SHUT_RDWR = 2
internal val SHUT_WR = 1
internal val SOCK_CLOEXEC = 524288
internal actual val SOCK_DGRAM = 2
internal val SOCK_NONBLOCK = 2048
internal actual val SOCK_RAW = 3
internal val SOCK_RDM = 4
internal val SOCK_SEQPACKET = 5
internal actual val SOCK_STREAM = 1
internal val SOL_ALG = 279
internal val SOL_CAN_BASE = 100
internal val SOL_CAN_RAW = 101
internal val SOL_HCI = 0
internal val SOL_IP = 0
internal val SOL_RDS = 276
internal actual val SOL_SOCKET = 1
internal val SOL_TCP = 6
internal val SOL_TIPC = 271
internal val SOL_UDP = 17
internal val SOMAXCONN = 4096
internal val SO_ACCEPTCONN = 30
internal val SO_BINDTODEVICE = 25
internal actual val SO_BROADCAST = 6
internal actual val SO_DEBUG = 1
internal val SO_DOMAIN = 39
internal val SO_DONTROUTE = 5
internal val SO_ERROR = 4
internal actual val SO_KEEPALIVE = 9
internal val SO_LINGER = 13
internal val SO_MARK = 36
internal actual val SO_OOBINLINE = 10
internal val SO_PASSCRED = 16
internal val SO_PASSSEC = 34
internal val SO_PEERCRED = 17
internal val SO_PEERSEC = 31
internal val SO_PRIORITY = 12
internal val SO_PROTOCOL = 38
internal actual val SO_RCVBUF = 8
internal val SO_RCVLOWAT = 18
internal val SO_RCVTIMEO = 20
internal actual val SO_REUSEADDR = 2
internal val SO_REUSEPORT = 15
internal actual val SO_SNDBUF = 7
internal val SO_SNDLOWAT = 19
internal val SO_SNDTIMEO = 21
internal val SO_TYPE = 3
internal val SO_VM_SOCKETS_BUFFER_MAX_SIZE = 2
internal val SO_VM_SOCKETS_BUFFER_MIN_SIZE = 1
internal val SO_VM_SOCKETS_BUFFER_SIZE = 0
internal val TCP_CONGESTION = 13
internal val TCP_CORK = 3
internal val TCP_DEFER_ACCEPT = 9
internal val TCP_FASTOPEN = 23
internal val TCP_INFO = 11
internal val TCP_KEEPCNT = 6
internal val TCP_KEEPIDLE = 4
internal val TCP_KEEPINTVL = 5
internal val TCP_LINGER2 = 8
internal val TCP_MAXSEG = 2
internal val TCP_NODELAY = 1
internal val TCP_NOTSENT_LOWAT = 25
internal val TCP_QUICKACK = 12
internal val TCP_SYNCNT = 7
internal val TCP_USER_TIMEOUT = 18
internal val TCP_WINDOW_CLAMP = 10
internal val TIPC_ADDR_ID = 3
internal val TIPC_ADDR_NAME = 2
internal val TIPC_ADDR_NAMESEQ = 1
internal val TIPC_CFG_SRV = 0
internal val TIPC_CLUSTER_SCOPE = 2
internal val TIPC_CONN_TIMEOUT = 130
internal val TIPC_CRITICAL_IMPORTANCE = 3
internal val TIPC_DEST_DROPPABLE = 129
internal val TIPC_HIGH_IMPORTANCE = 2
internal val TIPC_IMPORTANCE = 127
internal val TIPC_LOW_IMPORTANCE = 0
internal val TIPC_MEDIUM_IMPORTANCE = 1
internal val TIPC_NODE_SCOPE = 3
internal val TIPC_PUBLISHED = 1
internal val TIPC_SRC_DROPPABLE = 128
internal val TIPC_SUBSCR_TIMEOUT = 3
internal val TIPC_SUB_CANCEL = 4
internal val TIPC_SUB_PORTS = 1
internal val TIPC_SUB_SERVICE = 2
internal val TIPC_TOP_SRV = 1
internal val TIPC_WAIT_FOREVER = -1
internal val TIPC_WITHDRAWN = 2
internal val TIPC_ZONE_SCOPE = 1
internal val VMADDR_CID_ANY = 4294967295
internal val VMADDR_CID_HOST = 2
internal val VMADDR_PORT_ANY = 4294967295
internal val VM_SOCKETS_INVALID_VERSION = 4294967295
