/*
 * Copyright (C) 2020-2021 Lura Skye Revuwution.
 *
 * This file is part of Tinlok.
 *
 * Tinlok is dually released under the GNU Lesser General Public License,
 * Version 3 or later, or the Mozilla Public License 2.0.
 */

@file:Suppress("unused", "MayBeConstant", "SpellCheckingInspection")

package tf.lotte.tinlok.net.socket

internal val AF_APPLETALK = 16
internal val AF_BLUETOOTH = 32
internal actual val AF_INET = 2
internal actual val AF_INET6 = 23
internal val AF_IPX = 6
internal val AF_IRDA = 26
internal val AF_LINK = 33
internal val AF_SNA = 11
internal actual val AF_UNSPEC = 0
internal actual val AF_UNIX = 1
internal val BTPROTO_RFCOMM = 3
internal val EAGAIN = 11
internal val EAI_AGAIN = 11002
internal val EAI_BADFLAGS = 10022
internal val EAI_FAIL = 11003
internal val EAI_FAMILY = 10047
internal val EAI_MEMORY = 8
internal val EAI_NODATA = 11001
internal val EAI_NONAME = 11001
internal val EAI_SERVICE = 10109
internal val EAI_SOCKTYPE = 10044
internal val EBADF = 9
internal val EWOULDBLOCK = 10035
internal val INADDR_ALLHOSTS_GROUP = -536870911
internal val INADDR_ANY = 0
internal val INADDR_BROADCAST = -1
internal val INADDR_LOOPBACK = 2130706433
internal val INADDR_MAX_LOCAL_GROUP = -536870657
internal val INADDR_NONE = -1
internal val INADDR_UNSPEC_GROUP = -536870912
internal val IPPORT_RESERVED = 1024
internal val IPPORT_USERRESERVED = 5000
internal val IPPROTO_AH = 51
internal val IPPROTO_CBT = 7
internal val IPPROTO_DSTOPTS = 60
internal val IPPROTO_EGP = 8
internal val IPPROTO_ESP = 50
internal val IPPROTO_FRAGMENT = 44
internal val IPPROTO_GGP = 3
internal val IPPROTO_HOPOPTS = 0
internal val IPPROTO_ICLFXBM = 78
internal actual val IPPROTO_ICMP = 1
internal val IPPROTO_ICMPV6 = 58
internal val IPPROTO_IDP = 22
internal val IPPROTO_IGMP = 2
internal val IPPROTO_IGP = 9
internal actual val IPPROTO_IP = 0
internal val IPPROTO_IPV4 = 4
internal val IPPROTO_IPV6 = 41
internal val IPPROTO_L2TP = 115
internal val IPPROTO_MAX = 256
internal val IPPROTO_ND = 77
internal val IPPROTO_NONE = 59
internal val IPPROTO_PGM = 113
internal val IPPROTO_PIM = 103
internal val IPPROTO_PUP = 12
internal val IPPROTO_RAW = 255
internal val IPPROTO_RDP = 27
internal val IPPROTO_ROUTING = 43
internal val IPPROTO_SCTP = 132
internal val IPPROTO_ST = 5
internal actual val IPPROTO_TCP = 6
internal actual val IPPROTO_UDP = 17
internal val IPV6_CHECKSUM = 26
internal val IPV6_DONTFRAG = 14
internal val IPV6_HOPLIMIT = 21
internal val IPV6_HOPOPTS = 1
internal val IPV6_JOIN_GROUP = 12
internal val IPV6_LEAVE_GROUP = 13
internal val IPV6_MULTICAST_HOPS = 10
internal val IPV6_MULTICAST_IF = 9
internal val IPV6_MULTICAST_LOOP = 11
internal val IPV6_PKTINFO = 19
internal val IPV6_RECVRTHDR = 38
internal val IPV6_RECVTCLASS = 40
internal val IPV6_RTHDR = 32
internal val IPV6_TCLASS = 39
internal val IPV6_UNICAST_HOPS = 4
internal val IPV6_V6ONLY = 27
internal val IP_ADD_MEMBERSHIP = 12
internal val IP_DROP_MEMBERSHIP = 13
internal val IP_HDRINCL = 2
internal val IP_MULTICAST_IF = 9
internal val IP_MULTICAST_LOOP = 11
internal val IP_MULTICAST_TTL = 10
internal val IP_OPTIONS = 1
internal val IP_RECVDSTADDR = 25
internal val IP_TOS = 3
internal val IP_TTL = 4
internal val NI_DGRAM = 16
internal val NI_MAXHOST = 1025
internal val NI_MAXSERV = 32
internal val NI_NAMEREQD = 4
internal val NI_NOFQDN = 1
internal val NI_NUMERICHOST = 2
internal val NI_NUMERICSERV = 8
internal val RCVALL_MAX = 3
internal val RCVALL_OFF = 0
internal val RCVALL_ON = 1
internal val RCVALL_SOCKETLEVELONLY = 2
internal val SHUT_RD = 0
internal val SHUT_RDWR = 2
internal val SHUT_WR = 1
internal val SIO_KEEPALIVE_VALS = 2550136836
internal val SIO_LOOPBACK_FAST_PATH = 2550136848
internal val SIO_RCVALL = 2550136833
internal actual val SOCK_DGRAM = 2
internal actual val SOCK_RAW = 3
internal val SOCK_RDM = 4
internal val SOCK_SEQPACKET = 5
internal actual val SOCK_STREAM = 1
internal val SOL_IP = 0
internal actual val SOL_SOCKET = 65535
internal val SOL_TCP = 6
internal val SOL_UDP = 17
internal val SOMAXCONN = 2147483647
internal val SO_ACCEPTCONN = 2
internal actual val SO_BROADCAST = 32
internal actual val SO_DEBUG = 1
internal val SO_DONTROUTE = 16
internal val SO_ERROR = 4103
internal val SO_EXCLUSIVEADDRUSE = -5
internal actual val SO_KEEPALIVE = 8
internal val SO_LINGER = 128
internal actual val SO_OOBINLINE = 256
internal actual val SO_RCVBUF = 4098
internal val SO_RCVLOWAT = 4100
internal val SO_RCVTIMEO = 4102
internal actual val SO_REUSEADDR = 4
internal actual val SO_SNDBUF = 4097
internal val SO_SNDLOWAT = 4099
internal val SO_SNDTIMEO = 4101
internal val SO_TYPE = 4104
internal val SO_USELOOPBACK = 64
internal val TCP_NODELAY = 1
internal val TCP_FASTOPEN = 15
internal val TCP_KEEPCNT = 16
internal val TCP_KEEPIDLE = 3
internal val TCP_KEEPINTVL = 17
internal val TCP_MAXSEG = 4
